# Copyright (C) 2026 Ben Weis <ben@springbird.app>
# Based on Lead, copyright (C) 2026 PlanetScale
#
# See LICENSE in the repository root for license terms.

[package]
name = "tinql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
thiserror.workspace = true
rustc-hash.workspace = true
regex-automata = "0.4"
regex-syntax = "0.8"
tokenizer = { path = "../tokenizer" }
boldi-vigna = { path = "../boldi-vigna" }
segment = { path = "../segment" }

[dev-dependencies]
proptest = "1"
